name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 17, 21 ]         # Support java LTS and latest
        clojure: [ 11 ]

    name: Clojure ${{ matrix.clojure }} Java ${{ matrix.jdk }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          leiningen: latest
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-
      # - name: Execute tests
      #   run: clojure -M:test
      - name: Build uberjar
        run: lein uberjar
#      - name: archive uberjar
#        uses: actions/upload-artifact@v3
#        with:
#          name: findjar-standalone-jar
#          path: |
#            target/findjar-*-standalone.jar
#            gen-resources/build/version.edn
#            LICENSE
